services:
  - type: web
    name: proyecto-avanzada
    env: docker
    dockerfilePath: ./Dockerfile # Ruta al Dockerfile (en la raíz)
    plan: free                  # O el plan que uses
    autoDeploy: true            # Opcional, activa despliegues automáticos
    envVars:
      - key: ENVIRONMENT
        value: production
